services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "5005:5000"
    environment:
      - MONGO_URI=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/${MONGO_DB_NAME}?authSource=admin
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads

  mongodb:
    image: mongo:4.4
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
    healthcheck:
      test: ["CMD", "mongo", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mongodb_data:/data/db
      - ./mongodb-int:/docker-entrypoint-initdb.d

volumes:
  mongodb_data:
